// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/meal": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new meal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Create a meal",
                "parameters": [
                    {
                        "description": "Meal Data",
                        "name": "meal",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Meal"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    }
                }
            }
        },
        "/meal/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a meal by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Get a meal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Meal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Meal"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete a meal by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Delete a meal",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Meal ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    }
                }
            }
        },
        "/meals": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Get meals for a user filtered by date range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meals"
                ],
                "summary": "Get meals by date",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Get meals not after this date (YYYY-MM-DD)",
                        "name": "date_not_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Get meals not before this date (YYYY-MM-DD)",
                        "name": "date_not_before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/meal.mealGetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "meal.mealGetResponse": {
            "type": "object",
            "properties": {
                "meals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Meal"
                    }
                }
            }
        },
        "models.Meal": {
            "type": "object",
            "required": [
                "name",
                "timestamp"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "meal_entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MealEntry"
                    }
                },
                "name": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.MealEntry": {
            "type": "object",
            "required": [
                "name",
                "quantity",
                "quantity_unit"
            ],
            "properties": {
                "alcohol": {
                    "type": "number"
                },
                "beta_carotene": {
                    "type": "number"
                },
                "calcium": {
                    "description": "Minerals",
                    "type": "number"
                },
                "carbohydrates": {
                    "description": "Macros: Carbohydrates \u0026 Sugars",
                    "type": "number"
                },
                "carbohydrates_unit": {
                    "type": "string"
                },
                "cholesterol": {
                    "type": "number"
                },
                "copper": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "energy_kcal": {
                    "description": "Energy",
                    "type": "number"
                },
                "energy_kcal_unit": {
                    "type": "string"
                },
                "energy_kj": {
                    "type": "number"
                },
                "energy_kj_unit": {
                    "type": "string"
                },
                "fat": {
                    "description": "Macros: Fats",
                    "type": "number"
                },
                "fat_unit": {
                    "type": "string"
                },
                "fiber": {
                    "type": "number"
                },
                "fructose": {
                    "type": "number"
                },
                "fruits_veg_legumes_est": {
                    "type": "number"
                },
                "fruits_veg_nuts_est": {
                    "type": "number"
                },
                "galactose": {
                    "type": "number"
                },
                "glucose": {
                    "type": "number"
                },
                "iodine": {
                    "type": "number"
                },
                "iron": {
                    "type": "number"
                },
                "lactose": {
                    "type": "number"
                },
                "magnesium": {
                    "type": "number"
                },
                "maltose": {
                    "type": "number"
                },
                "manganese": {
                    "type": "number"
                },
                "monounsaturated_fat": {
                    "type": "number"
                },
                "monounsaturated_fat_unit": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nova_group": {
                    "description": "Scores \u0026 Estimates",
                    "type": "integer"
                },
                "nutrition_score_fr": {
                    "type": "integer"
                },
                "pantothenic_acid": {
                    "type": "number"
                },
                "phosphorus": {
                    "type": "number"
                },
                "phylloquinone": {
                    "type": "number"
                },
                "polyols": {
                    "type": "number"
                },
                "polyunsaturated_fat": {
                    "type": "number"
                },
                "polyunsaturated_fat_unit": {
                    "type": "string"
                },
                "potassium": {
                    "type": "number"
                },
                "proteins": {
                    "description": "Macros: Proteins \u0026 Others",
                    "type": "number"
                },
                "proteins_unit": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "quantity_unit": {
                    "type": "string"
                },
                "salt": {
                    "description": "Salt \u0026 Sodium",
                    "type": "number"
                },
                "salt_unit": {
                    "type": "string"
                },
                "saturated_fat": {
                    "type": "number"
                },
                "saturated_fat_unit": {
                    "type": "string"
                },
                "selenium": {
                    "type": "number"
                },
                "sodium": {
                    "type": "number"
                },
                "sodium_unit": {
                    "type": "string"
                },
                "starch": {
                    "type": "number"
                },
                "sucrose": {
                    "type": "number"
                },
                "sugars": {
                    "type": "number"
                },
                "trans_fat": {
                    "type": "number"
                },
                "trans_fat_unit": {
                    "type": "string"
                },
                "vitamin_a": {
                    "description": "Vitamins",
                    "type": "number"
                },
                "vitamin_b1": {
                    "type": "number"
                },
                "vitamin_b12": {
                    "type": "number"
                },
                "vitamin_b2": {
                    "type": "number"
                },
                "vitamin_b6": {
                    "type": "number"
                },
                "vitamin_b9": {
                    "type": "number"
                },
                "vitamin_c": {
                    "type": "number"
                },
                "vitamin_d": {
                    "type": "number"
                },
                "vitamin_e": {
                    "type": "number"
                },
                "vitamin_pp": {
                    "type": "number"
                },
                "water": {
                    "type": "number"
                },
                "zinc": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Meal Service API",
	Description:      "This is the API for the Meal Service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
